# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\xixkh\Desktop\WAM Python Project\Res\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 50, 131, 61))
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\"; color: rgb(243, 243, 243)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 141, 61))
        self.label_2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 141, 61))
        self.label_3.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(200, 180, 201, 41))
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(200, 280, 201, 41))
        self.password.setObjectName("password")
        self.login = QtWidgets.QPushButton(Dialog)
        self.login.setGeometry(QtCore.QRect(300, 430, 141, 41))
        self.login.setStyleSheet("background-color:rgb(167, 168, 167); font-size:14px")
        self.login.setObjectName("login")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(200, 350, 161, 16))
        self.label_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.clickhere = QtWidgets.QPushButton(Dialog)
        self.clickhere.setGeometry(QtCore.QRect(340, 350, 91, 21))
        self.clickhere.setStyleSheet("background-color:#363636; font-size:14px; color: rgb(230, 230, 230)")
        self.clickhere.setObjectName("clickhere")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login "))
        self.label_2.setText(_translate("Dialog", "Username"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.login.setText(_translate("Dialog", "Login"))
        self.label_4.setText(_translate("Dialog", "Don\'t have an account? "))
        self.clickhere.setText(_translate("Dialog", "Click here!"))
